services:
  laravel.test:
    build:
      context: ./vendor/laravel/sail/runtimes/8.4
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.4/app
    tty: true
    ports:
      - '8008:80'
      - '8009:8080'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    depends_on:
      - psql
      - redis
      - typesense
      - minio
  auth.test:
    build:
      context: ./vendor/laravel/sail/runtimes/8.4
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.4/app
    tty: true
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    depends_on:
      - laravel.test
  psql:
    image: 'postgres:17'
    environment:
      PGPASSWORD: laravel
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel
    ports:
      - '5900:5432'
    networks:
      - sail
  redis:
    image: 'redis:alpine'
    ports:
      - '5901:6379'
    volumes:
      - 'sail-redis:/data'
    networks:
      - sail
  minio:
    image: 'minio/minio:latest'
    ports:
      - '5903:9000'
      - '5904:8900'
    environment:
      MINIO_ROOT_USER: sail
      MINIO_ROOT_PASSWORD: password
    volumes:
      - 'sail-minio:/data'
    networks:
      - sail
    command: 'minio server /data --console-address ":8900"'
  insight:
    image: redis/redisinsight:2.58.0
    restart: unless-stopped
    volumes:
      - sail-insight:/data
    environment:
      - RI_APP_PORT=5540
    networks:
      - sail
    ports:
      - "5905:5540"
  typesense:
    image: 'typesense/typesense:27.1'
    environment:
      TYPESENSE_DATA_DIR: '${TYPESENSE_DATA_DIR:-/typesense-data}'
      TYPESENSE_API_KEY: '${TYPESENSE_API_KEY:-xyz}'
      TYPESENSE_ENABLE_CORS: '${TYPESENSE_ENABLE_CORS:-true}'
    ports:
      - '5906:8108'
    volumes:
      - 'sail-typesense:/typesense-data'
    networks:
      - sail
networks:
  sail:
    driver: bridge
volumes:
  sail-redis:
  sail-typesense:
  sail-minio:
  sail-insight:
